### ISSUE TITLE
Change dependency from mbedtls to mbedtls2

### ISSUE THREAD

**Issue by SirToffski** [HamletDuFromage/slippi-online-git-PKGBUILD#2]
Arch has updated [mbedtls](https://gitlab.archlinux.org/archlinux/packaging/packages/mbedtls) version to 3.4.0. Version 2.28.3 is now a separate package [mbedtls2](https://gitlab.archlinux.org/archlinux/packaging/packages/mbedtls2). This is the package that slippi dolphin depends on for build and runtime.

```diff
--- PKGBUILD.old        2023-05-28 15:37:19.940532467 -0300
+++ PKGBUILD.new        2023-05-28 15:38:26.840782806 -0300
@@ -14,7 +14,7 @@
 license=('GPL2')
 depends=(
        'alsa-lib' 'bluez-libs' 'enet' 'hidapi' 'libevdev' 'libgl' 'libpng'
-       'libpulse' 'libx11' 'libxi' 'libxrandr' 'lzo' 'mbedtls' 'pugixml' 'qt5-base'
+       'libpulse' 'libx11' 'libxi' 'libxrandr' 'lzo' 'mbedtls2' 'pugixml' 'qt5-base'
        'sfml' 'zlib' 'webkit2gtk'
        'libavcodec.so' 'libavformat.so' 'libavutil.so' 'libcurl.so'
        'libminiupnpc.so' 'libswscale.so' 'libudev.so' 'libusb-1.0.so'
```

**Comment by HamletDuFromage** [comment]
Won't compile on my machine

```
/home/[redacted]/Documents/Ishiiruka/Source/Core/Core/Movie.cpp:9:10: fatal error: mbedtls/config.h: No such file or directory
    9 | #include <mbedtls/config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Source/Core/Core/CMakeFiles/core.dir/build.make:272: Source/Core/Core/CMakeFiles/core.dir/Movie.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/[redacted]/Documents/Ishiiruka/Source/Core/Core/IPC_HLE/WII_Socket.h:57,
                 from /home/[redacted]/Documents/Ishiiruka/Source/Core/Core/Core.cpp:59:
/home/[redacted]/Documents/Ishiiruka/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_net_ssl.h:12:10: fatal error: mbedtls/net.h: No such file or directory
   12 | #include <mbedtls/net.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Source/Core/Core/CMakeFiles/core.dir/build.make:152: Source/Core/Core/CMakeFiles/core.dir/Core.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1206: Source/Core/Core/CMakeFiles/core.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

It'd need a patch, I'll look into it tomorrow. Feel free to submit a PR if you figure it out before me

**Comment by SirToffski** [comment]
Hmm, weird - I can build it OK in a clean chroot on vanilla Arch. Those build errors are the same ones I had and were resolved after updating PKGBUILD to use `mbedtls2`.

Just double-checked and it still compiles fine here. Here's the [PKGBUILD](https://gist.githubusercontent.com/SirToffski/59f0f42d52b5b6b1d6113b34cf03a1cf/raw/d70ccfe61a5cc90badea44b825098dd5c06a8ef0/PKGBUILD) I used to build it, as well as my [makepkg.conf](https://gist.githubusercontent.com/SirToffski/59f0f42d52b5b6b1d6113b34cf03a1cf/raw/d70ccfe61a5cc90badea44b825098dd5c06a8ef0/makepkg.conf) and the [build log](https://gist.githubusercontent.com/SirToffski/59f0f42d52b5b6b1d6113b34cf03a1cf/raw/d70ccfe61a5cc90badea44b825098dd5c06a8ef0/build.log)

**Comment by HamletDuFromage** [comment]
Maybe it doesn't compile when you got both mbedtls2 and mbedtls installed since it doesn't look for `/usr/lib/mbedtls2/ `? I can actually compile it just fine with this patch, which I PR'd to slippi-online

https://github.com/dolphin-emu/dolphin/pull/11847

**Comment by SirToffski** [comment]
> Maybe it doesn't compile when you got both mbedtls2 and mbedtls installed since it doesn't look for `/usr/lib/mbedtls2/ `? I can actually compile it just fine with this patch, which I PR'd to slippi-online
> 
> 
> 
> https://github.com/dolphin-emu/dolphin/pull/11847

Makes sense! Chroot would only have had mbedtls2 installed.

In this case I shall close the issue, since fixing this upstream makes more sense.
